server:
  port: 7200


# 可以通过yml配置，也可以代码在configuration->set
#hbase:
#  config:
#    hbase.master: 172.28.0.34:2181
#    hbase.zookeepre.quorum: 172.28.0.34:2181
#        root-dir: /hbase
#      client:
#        username: root
#        password: Map0935H@eY3
hbase:
  zookeeper.quorum: 10.24.50.17:2181,10.24.50.2:2181,10.24.50.11:2181
spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy:MM:dd HH:mm:ss
