server:
  port: 7100

spring:
  kafka:
    bootstrap-servers: 172.28.0.4:9092
    producer:
      buffer-memory: 40960
      retries: 0
      batch-size: 4096
      acks: 1
    consumer:
      group-id: test_group
      # smallest和largest才有效，如果smallest重新0开始读取，如果是largest从logfile的offset读取。一般情况下我们都是设置smallest
      auto-offset-reset: earliest
      # 设置自动提交offset
      enable-auto-commit: true
      # 如果'enable.auto.commit'为true，则消费者偏移自动提交给Kafka的频率（以毫秒为单位），默认值为5000。
      auto-commit-interval: 100
      max-poll-records: 5