server:
  port: 7070

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: manage_route
          uri: http://localhost:9000
          predicates:
            - Path=/report/**,/cache/**
        - id: es_route
          uri: http://localhost:9200
          predicates:
            - Path=/search/**
        - id: hbase_route
          uri: http://localhost:7200
          predicates:
            - Path=/hbase/**
        - id: kafka_route
          uri: http://localhost:7100
          predicates:
            - Path=/message/**
        - id: thrid_call_route
          uri: http://localhost:7001
          predicates:
            - Path=/thrid/**
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
