server:
  port: 9000

spring:
  application:
    name: manage-api
  datasource:
    url: jdbc:mysql://localhost:3306/manage?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jackson:
    time-zone: GMT+8
  redis:
    database: 0
    host: 192.168.43.60
    password: 2292984881

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848