server:
  port: 7400
spring:
  data:
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
    rest:
      uris: http://172.28.0.24:9200
      username: elastic
      password: elastic@20%es19

