server:
  port: 9000

spring:
  application:
    name: nxe-dev
  datasource:
    url: jdbc:mysql://172.28.0.7:3306/access_domain?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Mys$9102qdJd3
  jackson:
    time-zone: GMT+8


mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.kisro.cloud.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
